     // - 定义线的数据
     var lineData = [
        {
            from:{
                x:1038,
                y:254
            },
            to:{
                x:1131,
                y:254
            },
            color:'#2480ad'
        },
        {
           from:{
               x:909,
               y:277
           },
           to:{
               x:909,
               y:557
           },
           color:'#2480ad'
       },
       {
          from:{
              x:909,
              y:318
          },
          to:{
              x:693,
              y:318
          },
          color:'#2480ad'
      },
      {
           from:{
               x:909,
               y:478
           },
           to:{
               x:1130,
               y:478
           },
           color:'#2480ad'
       },
       {
           from:{
               x:909,
               y:557
           },
           to:{
               x:129,
               y:557
           },
           color:'#2480ad'
       },
       {
           from:{
               x:909,
               y:557
           },
           to:{
               x:1700,
               y:557
           },
           color:'#2480ad'
       },
       {
           from:{
               x:909,
               y:557
           },
           to:{
               x:909,
               y:622
           },
           color:'#2480ad'
       },
       {
           from:{
               x:129,
               y:557
           },
           to:{
               x:129,
               y:857
           },
           color:'#2480ad'
       },
       {
           from:{
               x:1700,
               y:557
           },
           to:{
               x:1700,
               y:857
           },
           color:'#2480ad'
       },
       {
           from:{
               x:129,
               y:648
           },
           to:{
               x:151,
               y:648
           },
           color:'#2480ad'
       },
       {
           from:{
               x:129,
               y:721
           },
           to:{
               x:151,
               y:721
           },
           color:'#2480ad'
       },
       {
           from:{
               x:129,
               y:790
           },
           to:{
               x:151,
               y:790
           },
           color:'#2480ad'
       },
       {
           from:{
               x:129,
               y:860
           },
           to:{
               x:151,
               y:860
           },
           color:'#2480ad'
       },
       {
           from:{
               x:1700,
               y:648
           },
           to:{
               x:1668,
               y:648
           },
           color:'#2480ad'
       },
       {
           from:{
               x:1700,
               y:721
           },
           to:{
               x:1668,
               y:721
           },
           color:'#2480ad'
       },
       {
           from:{
               x:1700,
               y:790
           },
           to:{
               x:1668,
               y:790
           },
           color:'#2480ad'
       },
       {
           from:{
               x:1700,
               y:860
           },
           to:{
               x:1668,
               y:860
           },
           color:'#2480ad'
       }
   ]